### ISSUE TITLE
Make subscribe send alongside with contractName, the new data in that state

### ISSUE THREAD

**Issue by mtmr0x** [nucleojs/nucleo#21]
## Task
When a listener be executed from inside Nucleo, increment in the object the new data being stored as copy.

## Checklist

- [x] Make the object copy inside `indexSearch`;
- [x] Increment the subscriber arguments the data;
- [x] Send data to subscriber
- [x] Enhance documentation for subscribers and listeners, explaining the flow
